# Generated by Django 2.1.2 on 2018-10-14 03:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('contact_email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('employees_required', models.IntegerField()),
                ('employees_assigned', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Amodel',
        ),
    ]
