# Generated by Django 2.1.2 on 2018-10-15 17:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_auto_20181013_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='Monday', max_length=9)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('employees_required', models.IntegerField()),
                ('employees_assigned', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
