# Generated by Django 2.1.2 on 2018-10-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_delete_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
