# Generated by Django 2.1.2 on 2018-10-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_csv_export'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv_Export',
        ),
    ]
