# Generated by Django 2.1.2 on 2018-10-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_delete_csv_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=254)),
                ('start_date', models.DateField()),
                ('description', models.CharField(max_length=254)),
            ],
        ),
    ]
