# Generated by Django 2.1.2 on 2018-10-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0004_auto_20181015_1412'),
        ('admin_dashboard', '0007_scheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_export',
            fields=[
                ('user_schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee_dashboard.User_Schedule')),
            ],
            bases=('employee_dashboard.user_schedule',),
        ),
    ]
