# Generated by Django 2.1.2 on 2018-10-17 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_csv_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv_export',
            name='user_schedule_ptr',
        ),
        migrations.AlterField(
            model_name='shift',
            name='employees_assigned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
        migrations.DeleteModel(
            name='CSV_export',
        ),
    ]
