# Generated by Django 2.1.2 on 2018-10-17 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_auto_20181017_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employees_assigned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
