# Generated by Django 2.1.2 on 2018-10-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_auto_20181017_1138'),
        ('admin_dashboard', '0010_auto_20181017_1013'),
    ]

    operations = [
    ]
