# Generated by Django 2.1.2 on 2018-10-14 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dashboard', '0002_auto_20181013_2013'),
        ('employee_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priotity', models.IntegerField(choices=[(1, 'highest'), (2, 'Medium'), (3, 'Lowest')], default=3)),
                ('status', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.Schedules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shedule_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Amodel',
        ),
    ]
