# Generated by Django 2.1.2 on 2018-10-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_shift'),
        ('employee_dashboard', '0002_auto_20181013_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_schedule',
            name='shift_id',
        ),
        migrations.AddField(
            model_name='user_schedule',
            name='selected_shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.Shift'),
            preserve_default=False,
        ),
    ]
