# Generated by Django 2.1.2 on 2018-10-17 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0004_auto_20181015_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_schedule',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Highest'), (2, 'Medium'), (3, 'Lowest')], default=3),
        ),
        migrations.AlterField(
            model_name='user_schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
