# Generated by Django 2.1.2 on 2018-10-18 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dashboard', '0010_auto_20181017_1013'),
        ('employee_dashboard', '0006_auto_20181017_2206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_schedule',
            unique_together={('user', 'selected_shift', 'priority')},
        ),
    ]
