# Generated by Django 2.1.2 on 2018-10-18 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_dashboard', '0007_auto_20181018_0821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_schedule',
            unique_together={('user', 'priority')},
        ),
    ]
