# Generated by Django 2.1.2 on 2018-10-18 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dashboard', '0010_auto_20181017_1013'),
        ('employee_dashboard', '0008_auto_20181018_0823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_schedule',
            unique_together={('user', 'priority', 'selected_shift')},
        ),
    ]
