# Generated by Django 2.1.2 on 2018-10-18 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_auto_20181017_1013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_dashboard', '0009_auto_20181018_0826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_schedule',
            unique_together={('user', 'selected_shift')},
        ),
    ]
